entity: norwai
project: norwai
program: norwai_county_train.py
method: grid
metric:
  name: test_acc
  goal: maximize
parameters:
  epochs:
    values: [30]
  lr:
    values: [0.0001, 0.01]
  lr_decay:
    values: [0.95]
  batch_size:
    values: [32]
  architecture:
    values: [ResNet152, EfficientNet]
  pretrained:
    values: [False]
  dataset:
    values: [full]