entity: norwai
project: norwai
program: norwai_regression_train.py
method: grid
metric:
  name: test_loss
  goal: minimize
parameters:
  epochs:
    values: [30]
  lr:
    values: [0.0001]
  lr_decay:
    values: [0.95]
  batch_size:
    values: [32]
  architecture:
    values: [ResNet152, EfficientNet]
  pretrained:
    values: [True]
  dataset:
    values: [full]